linters:
  disable-all: true
  enable:
  - asciicheck
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - errcheck
  - gci
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - golint
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - nolintlint
  - prealloc
  - rowserrcheck
  - scopelint
  - staticcheck
  - structcheck
  - stylecheck
  - testpackage
  - typecheck
  - unconvert
  - unparam
  - varcheck
  - godot
  - whitespace

linters-settings:
  gci:
    local-prefixes: sigs.k8s.io/cluster-api

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  # We are disabling default golangci exclusions because we want to help reviewers to focus on reviewing the most relevant
  # changes in PRs and avoid nitpicking.
  exclude-use-default: false
  # List of regexps of issue texts to exclude, empty list by default.
  exclude:
    - Using the variable on range scope `(tc)|(rt)|(tt)|(test)|(testcase)|(testCase)` in function literal
    - "G108: Profiling endpoint is automatically exposed on /debug/pprof"
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
    # The following are being worked on to remove their exclusion. This list should be reduced or go away all together over time.
    # If it is decided they will not be addressed they should be moved above this comment.
    - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
    - package comment should be of the form "Package (.+) ..."
    - Subprocess launch(ed with variable|ing should be audited)
    - (Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)
    - (G104|G307)

run:
  timeout: 10m
  skip-files:
    - "zz_generated.*\\.go$"
    - ".*conversion.*\\.go$"
  skip-dirs:
    - third_party
  allow-parallel-runners: true
