# Netlify build instructions 
[build]
    command = "./hack/build-gitbook.sh"
    publish = "docs/book/_book"

# The redirects below have been temporarily disabled until the
# domain `cluster-api.sigs.k8s.io` has been created. Cf.
# https://github.com/kubernetes/k8s.io/pull/267

## Standard Netlify redirects
#[[redirects]]
#    from = "https://kubernetes-sigs-cluster-api.netlify.com/*"
#    to = "https://cluster-api.sigs.k8s.io/:splat"
#    status = 301
#    force = true
#
## HTTP-to-HTTPS rules
#[[redirects]]
#    from = "http://go.cluster-api.sigs.k8s.io/*"
#    to = "https://go.cluster-api.sigs.k8s.io/:splat"
#    status = 301
#    force = true
#
#[[redirects]]
#    from = "http://kubernetes-sigs-cluster-api.netlify.com/*"
#    to = "http://cluster-api.sigs.k8s.io/:splat"
#    status = 301
#    force = true
